server:
  port: 8081
spring:
  application:
    name: conta
  datasource:
    url: jdbc:mysql://localhost:3305/contadb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect